# Generated by Django 5.2.8 on 2025-11-22 02:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo_compatible', models.CharField(blank=True, help_text='Modelos de vehículo compatibles', max_length=200)),
                ('cantidad_stock', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(default=5, help_text='Cantidad mínima en stock')),
                ('ubicacion_almacen', models.CharField(blank=True, help_text='Ubicación en el almacén', max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=10)),
                ('precio_proveedor', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del proveedor', max_digits=10, null=True)),
                ('proveedor_principal', models.CharField(blank=True, max_length=200)),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=7, help_text='Días de entrega del proveedor')),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repuesto de Vehículo',
                'verbose_name_plural': 'Repuestos de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_carga_kg', models.DecimalField(decimal_places=2, help_text='Capacidad máxima en kg', max_digits=10)),
                ('capacidad_volumen_m3', models.DecimalField(decimal_places=2, help_text='Volumen máximo en m³', max_digits=10)),
                ('consumo_combustible_km', models.DecimalField(decimal_places=2, help_text='Consumo por km', max_digits=8)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('emergencia', 'Emergencia')], max_length=20)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('aplazado', 'Aplazado')], default='programado', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('kilometraje_actual', models.PositiveIntegerField(help_text='Kilometraje del vehículo en el momento del mantenimiento')),
                ('fecha_programada', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Duración en horas', max_digits=6, null=True)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, help_text='Costo de mano de obra', max_digits=10)),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, help_text='Costo de repuestos', max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, help_text='Costo total del mantenimiento', max_digits=10)),
                ('proveedor_servicio', models.CharField(blank=True, help_text='Taller o proveedor del servicio', max_length=200)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('factura_numero', models.CharField(blank=True, max_length=50)),
                ('garantia_meses', models.PositiveIntegerField(blank=True, help_text='Meses de garantía del servicio', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('trabajo_realizado', models.TextField(blank=True, help_text='Descripción detallada del trabajo realizado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento de Vehículo',
                'verbose_name_plural': 'Mantenimientos de Vehículos',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='UsoRepuestoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo unitario al momento del uso', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_utilizados', to='flota.mantenimientovehiculo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='flota.repuestovehiculo')),
            ],
            options={
                'verbose_name': 'Uso de Repuesto',
                'verbose_name_plural': 'Usos de Repuestos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_placa', models.CharField(help_text='Número de patente/placa', max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('año_fabricacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)])),
                ('numero_chasis', models.CharField(help_text='Número de chasis/VIN', max_length=50, unique=True)),
                ('numero_motor', models.CharField(help_text='Número de motor', max_length=50, unique=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, help_text='Kilometraje actual')),
                ('tipo_combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('gas', 'Gas'), ('electricidad', 'Electricidad'), ('hibrido', 'Híbrido')], default='diesel', max_length=20)),
                ('capacidad_tanque_litros', models.DecimalField(decimal_places=2, help_text='Capacidad del tanque en litros', max_digits=8)),
                ('consumo_promedio_km', models.DecimalField(decimal_places=2, help_text='Consumo promedio por km', max_digits=6)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio'), ('reparacion', 'En Reparación'), ('vendido', 'Vendido/Dado de Baja')], default='disponible', max_length=20)),
                ('ubicacion_actual', models.CharField(blank=True, help_text='Ubicación actual del vehículo', max_length=200)),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('compania_seguro', models.CharField(blank=True, max_length=100)),
                ('numero_poliza', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento_seguro', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_revision_tecnica', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_permiso_circulacion', models.DateField(blank=True, null=True)),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de adquisición', max_digits=12, null=True)),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor actual del vehículo', max_digits=12, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('kilometraje_ultimo_mantenimiento', models.PositiveIntegerField(blank=True, null=True)),
                ('proximo_mantenimiento_km', models.PositiveIntegerField(blank=True, null=True)),
                ('proximo_mantenimiento_fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales del vehículo')),
                ('es_activo', models.BooleanField(default=True, help_text='Vehículo activo en la flota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor_asignado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_conductor', to='conductores.conductor')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='flota.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['numero_placa'],
            },
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='flota.vehiculo'),
        ),
    ]
