# Generated by Django 5.2.8 on 2025-11-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bultos', to='envios.envio')),
            ],
            options={
                'unique_together': {('envio', 'codigo_barras')},
            },
        ),
    ]
