# Generated by Django 5.2.8 on 2025-11-21 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0004_envio_transportista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('envio_creado', 'Envío Creado'), ('envio_en_transito', 'Envío en Tránsito'), ('envio_en_reparto', 'Envío en Reparto'), ('envio_entregado', 'Envío Entregado'), ('envio_demorado', 'Envío Demorado'), ('envio_en_sucursal', 'Envío en Sucursal'), ('reclamo_actualizado', 'Reclamo Actualizado'), ('recordatorio_entrega', 'Recordatorio de Entrega'), ('confirmacion_horario', 'Confirmación de Horario'), ('multibulto_listo', 'Multibulto Listo para Retiro')], max_length=50, unique=True)),
                ('asunto_email', models.CharField(blank=True, max_length=200, null=True)),
                ('template_email_html', models.TextField(blank=True, null=True)),
                ('template_email_texto', models.TextField(blank=True, null=True)),
                ('template_sms', models.CharField(blank=True, max_length=160, null=True)),
                ('template_whatsapp', models.TextField(blank=True, max_length=1000, null=True)),
                ('template_push', models.CharField(blank=True, max_length=100, null=True)),
                ('variables_disponibles', models.TextField(help_text='Lista de variables disponibles: {{cliente_nombre}}, {{numero_envio}}, {{direccion}}, etc.')),
                ('prioridad', models.IntegerField(default=1, help_text='1-10, donde 10 es máxima prioridad')),
                ('es_urgente', models.BooleanField(default=False)),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('tiempo_espera_respuesta', models.IntegerField(default=24, help_text='Horas para esperar respuesta')),
                ('esta_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_email', models.BooleanField(default=True)),
                ('canal_sms', models.BooleanField(default=False)),
                ('canal_whatsapp', models.BooleanField(default=False)),
                ('canal_push', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(choices=[('inmediata', 'Inmediata'), ('diaria', 'Diaria (resumen)'), ('semanal', 'Semanal (resumen)')], default='inmediata', max_length=20)),
                ('hora_inicio', models.TimeField(default='08:00')),
                ('hora_fin', models.TimeField(default='20:00')),
                ('zona_horaria', models.CharField(default='America/Santiago', max_length=50)),
                ('esta_activa', models.BooleanField(default=True)),
                ('limite_diario', models.IntegerField(default=10)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('token_push', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='MetricaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_enviadas', models.IntegerField(default=0)),
                ('total_exitosas', models.IntegerField(default=0)),
                ('total_fallidas', models.IntegerField(default=0)),
                ('email_enviados', models.IntegerField(default=0)),
                ('email_exitosos', models.IntegerField(default=0)),
                ('sms_enviados', models.IntegerField(default=0)),
                ('sms_exitosos', models.IntegerField(default=0)),
                ('whatsapp_enviados', models.IntegerField(default=0)),
                ('whatsapp_exitosos', models.IntegerField(default=0)),
                ('tiempo_promedio_email_ms', models.IntegerField(default=0)),
                ('tiempo_promedio_sms_ms', models.IntegerField(default=0)),
                ('tiempo_promedio_whatsapp_ms', models.IntegerField(default=0)),
                ('tasa_apertura_email', models.FloatField(default=0.0)),
                ('tasa_click_email', models.FloatField(default=0.0)),
                ('reclamos_asociados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Métrica de Notificación',
                'verbose_name_plural': 'Métricas de Notificaciones',
                'unique_together': {('fecha',)},
            },
        ),
        migrations.CreateModel(
            name='NotificacionProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_destino', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('canal_programado', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('contenido_personalizado', models.JSONField(blank=True, help_text='Variables personalizadas para el template', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('error', 'Error'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('intentos_envio', models.IntegerField(default=0)),
                ('respuesta_cliente', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('log_envio', models.TextField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='envios.envio')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones_mejoradas.plantillanotificacion')),
            ],
            options={
                'verbose_name': 'Notificación Programada',
                'verbose_name_plural': 'Notificaciones Programadas',
                'ordering': ['fecha_programada', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_utilizado', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField()),
                ('fue_exitoso', models.BooleanField(default=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('proveedor_envio', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, null=True)),
                ('fue_leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('link_tracking', models.URLField(blank=True, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('notificacion_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='notificaciones_mejoradas.notificacionprogramada')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ListaExclusionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exclusion', models.CharField(choices=[('temporal', 'Temporal'), ('permanente', 'Permanente'), ('por_tipo', 'Por Tipo de Notificación')], default='temporal', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('razon', models.TextField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusiones_notificacion', to=settings.AUTH_USER_MODEL)),
                ('tipos_notificacion', models.ManyToManyField(blank=True, to='notificaciones_mejoradas.plantillanotificacion')),
            ],
            options={
                'verbose_name': 'Lista de Exclusión',
                'verbose_name_plural': 'Listas de Exclusión',
            },
        ),
    ]
