# Generated by Django 5.2.8 on 2025-11-21 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0004_envio_transportista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('shopify', 'Shopify'), ('amazon', 'Amazon'), ('woocommerce', 'WooCommerce'), ('prestashop', 'PrestaShop'), ('custom', 'Personalizado')], max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('store_url', models.URLField()),
                ('esta_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Plataformas E-commerce',
            },
        ),
        migrations.CreateModel(
            name='PedidoEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id_externo', models.CharField(max_length=100)),
                ('numero_orden', models.CharField(max_length=100)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_entrega', models.TextField()),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='CLP', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('datos_raw', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('envio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_ecommerce', to='envios.envio')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ecommerce.plataformaecommerce')),
            ],
            options={
                'verbose_name_plural': 'Pedidos E-commerce',
                'unique_together': {('plataforma', 'pedido_id_externo')},
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=50, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ecommerce.pedidoecommerce')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_tipo', models.CharField(max_length=100)),
                ('evento_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('advertencia', 'Advertencia'), ('error', 'Error')], default='info', max_length=20)),
                ('mensaje', models.TextField()),
                ('datos_recibidos', models.JSONField(blank=True, null=True)),
                ('datos_procesados', models.JSONField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('procesado_exitoso', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='ecommerce.plataformaecommerce')),
            ],
            options={
                'verbose_name_plural': 'Logs de Webhooks',
            },
        ),
    ]
