# Generated by Django 5.2.8 on 2025-12-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='ocurrido_en',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
