"""
Django settings for CorreosChile project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--6&n3dwn3xlo1w2pg2sl)3xpufmsxmfhag%scsi*%=8oown-o5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # opciones por si queremos agregar un router.

    # Aplicaciones propias
    'envios',
    'notificaciones',
    'reclamos',
    'seguimiento',
    'transportista',
    'usuarios',
    'ecommerce',
    'notificaciones_mejoradas',
    'clientes',
    'conductores',
    'flota',
    'paquetes',
    
    # Frameworks de terceros
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                    # CORS para API móvil
    'django.middleware.security.SecurityMiddleware',              # Middleware de seguridad
    'django.contrib.sessions.middleware.SessionMiddleware',       # Manejo de sesiones
    'django.middleware.common.CommonMiddleware',                  # Funcionalidades comunes necesarias
    'django.middleware.csrf.CsrfViewMiddleware',                  # Protección contra ataques CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',    # Autenticación de usuarios
    'django.contrib.messages.middleware.MessageMiddleware',       # Sistema de mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',     # Protección contra clickjacking
    'usuarios.middleware.SecurityLogMiddleware',                  # Registro de accesos no autorizados
]


ROOT_URLCONF = 'CorreosChile.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')  # Directorio global de templates
        ],
        'APP_DIRS': True,  # Busca templates dentro de las apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Necesario para acceder al objeto request
                'django.contrib.auth.context_processors.auth',  # Proporciona el usuario en los templates
                'django.template.context_processors.csrf',  # Protección CSRF
                'django.contrib.messages.context_processors.messages',
                'flota.context_processors.flota_badges',
            ],
        },
    },
]

WSGI_APPLICATION = 'CorreosChile.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from decouple import config
import pymysql

pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  # Directorio para archivos estáticos globales
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/usuarios/'
LOGOUT_REDIRECT_URL = '/usuarios/login/'

# Seguridad (HTTPS/TLS) configurable por entorno
from decouple import config
ENABLE_TLS = config('ENABLE_TLS', default=False, cast=bool)
SESSION_COOKIE_SECURE = ENABLE_TLS
CSRF_COOKIE_SECURE = ENABLE_TLS
SECURE_SSL_REDIRECT = ENABLE_TLS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if ENABLE_TLS:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
