# Generated by Django 5.2.8 on 2025-11-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('en_transito', 'en_transito'), ('en_planta', 'en_planta'), ('en_reparto', 'en_reparto'), ('entregado', 'entregado'), ('incidencia', 'incidencia')], max_length=20)),
                ('ubicacion', models.CharField(max_length=120)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='envios.envio')),
            ],
        ),
    ]
