# Generated by Django 5.2.8 on 2025-11-21 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('preferencias_email', models.BooleanField(default=True)),
                ('preferencias_sms', models.BooleanField(default=True)),
                ('preferencias_whatsapp', models.BooleanField(default=False)),
                ('preferencias_push', models.BooleanField(default=False)),
                ('mostrar_telefono', models.BooleanField(default=False)),
                ('mostrar_direccion', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ActividadCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Inicio de Sesión'), ('view_envio', 'Visto de Envío'), ('update_perfil', 'Actualización de Perfil'), ('cambio_direccion', 'Cambio de Dirección'), ('cambio_preferencias', 'Cambio de Preferencias'), ('descarga_reporte', 'Descarga de Reporte')], max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Actividad de Cliente',
                'verbose_name_plural': 'Actividades de Clientes',
                'db_table': 'actividades_cliente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Casa, Oficina, Casa de mis padres', max_length=100)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones especiales de entrega', null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Dirección de Entrega',
                'verbose_name_plural': 'Direcciones de Entrega',
                'db_table': 'direcciones_entrega',
                'ordering': ['-es_principal', '-fecha_creacion'],
            },
        ),
    ]
