# Generated by Django 5.2.8 on 2025-11-20 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('perdida', 'perdida'), ('danio', 'danio'), ('retraso', 'retraso'), ('otro', 'otro')], default='otro', max_length=20)),
                ('estado', models.CharField(choices=[('abierto', 'abierto'), ('en_revision', 'en_revision'), ('resuelto', 'resuelto'), ('cerrado', 'cerrado')], default='abierto', max_length=20)),
                ('descripcion', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envios.envio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
