# Generated by Django 5.2.8 on 2025-11-21 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0004_envio_transportista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('licencia_conducir', models.CharField(max_length=50, unique=True)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('vehiculo_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('descanso', 'En Descanso'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ultima_actualizacion_ubicacion', models.DateTimeField(blank=True, null=True)),
                ('dispositivo_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('token_notificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('app_version', models.CharField(blank=True, max_length=20, null=True)),
                ('total_envios_entregados', models.IntegerField(default=0)),
                ('total_kilometros_recorridos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio_jornada', models.TimeField(blank=True, null=True)),
                ('hora_fin_jornada', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('descanso', 'En Descanso'), ('fuera_servicio', 'Fuera de Servicio')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('descanso', 'En Descanso'), ('fuera_servicio', 'Fuera de Servicio')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='conductores.conductor')),
            ],
            options={
                'verbose_name': 'Historial de Estado del Conductor',
                'verbose_name_plural': 'Historial de Estados de Conductores',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('accidente', 'Accidente'), ('averia_vehiculo', 'Avería del Vehículo'), ('problema_entrega', 'Problema en Entrega'), ('problema_cliente', 'Problema con Cliente'), ('condiciones_climaticas', 'Condiciones Climáticas'), ('otro', 'Otro')], max_length=30)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='incidencias/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='incidencias/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='incidencias/')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='conductores.conductor')),
                ('envio_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='envios.envio')),
            ],
            options={
                'verbose_name': 'Incidencia del Conductor',
                'verbose_name_plural': 'Incidencias de Conductores',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='RutaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nombre_ruta', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('total_envios', models.IntegerField(default=0)),
                ('envios_entregados', models.IntegerField(default=0)),
                ('envios_fallidos', models.IntegerField(default=0)),
                ('distancia_total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo_estimado_minutos', models.IntegerField(default=0)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='conductores.conductor')),
            ],
            options={
                'verbose_name': 'Ruta del Conductor',
                'verbose_name_plural': 'Rutas de Conductores',
                'ordering': ['-fecha', 'nombre_ruta'],
                'unique_together': {('conductor', 'fecha', 'nombre_ruta')},
            },
        ),
        migrations.CreateModel(
            name='MetricasConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total_envios_entregados', models.IntegerField(default=0)),
                ('total_envios_fallidos', models.IntegerField(default=0)),
                ('total_kilometros_recorridos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo_total_trabajado_minutos', models.IntegerField(default=0)),
                ('eficiencia_entregas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiempo_promedio_entrega_minutos', models.IntegerField(default=0)),
                ('total_incidencias_reportadas', models.IntegerField(default=0)),
                ('puntuacion_general', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='conductores.conductor')),
            ],
            options={
                'verbose_name': 'Métrica del Conductor',
                'verbose_name_plural': 'Métricas de Conductores',
                'ordering': ['-fecha'],
                'unique_together': {('conductor', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='EnvioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_entrega', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('fallido', 'Fallido'), ('reprogramado', 'Reprogramado')], default='pendiente', max_length=20)),
                ('fecha_intento_entrega', models.DateTimeField(blank=True, null=True)),
                ('motivo_fallo', models.TextField(blank=True, null=True)),
                ('firma_digital', models.TextField(blank=True, null=True)),
                ('foto_entrega', models.ImageField(blank=True, null=True, upload_to='fotos_entrega/')),
                ('latitud_entrega', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_entrega', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='envios.envio')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_ruta', to='conductores.rutaconductor')),
            ],
            options={
                'verbose_name': 'Envío en Ruta',
                'verbose_name_plural': 'Envíos en Rutas',
                'ordering': ['orden_entrega'],
                'unique_together': {('ruta', 'envio')},
            },
        ),
    ]
